# **Importing Required Libraries**

In [9]:
import pandas as pd
import re

# **Loading the Dataset**

In [11]:
df = pd.read_csv("All_Electronics.csv")

df.head()

   1400532655  A2VS1WG9VKINXI  5.0  1290556800
0  1400532655   AHIMHJ4XUTGIM  5.0  1290297600
1  1400532655  A2YJ13OQZ6ZI5W  5.0  1290297600
2  1400532655   AVXCWZP85ZOU1  5.0  1290211200
3  1400532655   ASBYL5Y46JWIP  5.0  1468368000
4  1400532655  A3ST1L9RNEE0M8  1.0  1464480000

# **Dataset Structure**

In [12]:
df.columns = ['userId', 'productId', 'rating', 'timestamp']

df.head()

       userId       productId  rating   timestamp
0  1400532655   AHIMHJ4XUTGIM     5.0  1290297600
1  1400532655  A2YJ13OQZ6ZI5W     5.0  1290297600
2  1400532655   AVXCWZP85ZOU1     5.0  1290211200
3  1400532655   ASBYL5Y46JWIP     5.0  1468368000
4  1400532655  A3ST1L9RNEE0M8     1.0  1464480000

# **Data Preprocessing**

In [14]:
product_ratings = df.groupby('productId')['rating'].mean().reset_index()

product_ratings.head()

              productId  rating
0  A00520188LAK5MDHVWJZ     5.0
1  A0074881VC0UYNJ6S7H9     1.0
2  A0099217VFG1LPXHBBCY     5.0
3  A0099735VDZ3HDCAAYKL     5.0
4  A01112834ODK5R6L1MGU     2.0

# **Natural Language Query Input**

In [15]:
query = "show electronics products with rating above 4"

# **Query Parsing**

In [16]:
def extract_rating(query):

    pattern = r'rating\s*(above|over|greater than)\s*(\d)'

    match = re.search(pattern, query.lower())

    if match:
        return int(match.group(2))

    return None

# **Product Filtering**

In [17]:
def search_products(query):

    rating_value = extract_rating(query)

    if rating_value:

        results = product_ratings[
            product_ratings['rating'] > rating_value
        ]

        return results.head(10)

    return product_ratings.head(10)

# **Example Query Execution**

In [18]:
query = "show products with rating above 4"

results = search_products(query)

print(results)

               productId  rating
0   A00520188LAK5MDHVWJZ     5.0
2   A0099217VFG1LPXHBBCY     5.0
3   A0099735VDZ3HDCAAYKL     5.0
6   A0124017QGVJWIOKJ4QO     5.0
7   A0131882LZZ0DK3FBGVR     5.0
10  A0148968UM59JS3Y8D1M     5.0
11  A0152570SEDMXT3ILDC7     5.0
12  A0155336XOLO5756LN9M     5.0
14  A0163982I33BFLFLDW0T     5.0
15  A0171756YS9SZWSGR58F     5.0